import { useNavigate } from 'react-router-dom';
import { LEGAL_CONFIG } from '../legalConfig';
import './LegalPage.css';

function TermsOfService() {
  const navigate = useNavigate();

  return (
    <div className="legal-page">
      <div className="legal-content">
        <header className="legal-header">
          <button type="button" className="back-link" onClick={() => navigate(-1)}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M19 12H5M12 19l-7-7 7-7" />
            </svg>
            Back
          </button>
          <h1 className="legal-title">Terms of Service</h1>
          <p className="legal-date">Last updated: {LEGAL_CONFIG.termsOfServiceLastUpdated}</p>
        </header>

        <article className="legal-body">
          <section className="legal-section">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using AI Council ("the Service"), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section className="legal-section">
            <h2>2. Description of Service</h2>
            <p>
              AI Council is a multi-model AI deliberation platform that:
            </p>
            <ul>
              <li>Sends your questions to multiple AI models for independent analysis</li>
              <li>Conducts anonymized peer review between models</li>
              <li>Synthesizes a final answer from the highest-rated responses</li>
            </ul>
            <p>
              The Service uses third-party AI providers (OpenRouter, OpenAI, Google, Anthropic, xAI) to process queries.
            </p>
          </section>

          <section className="legal-section">
            <h2>3. Account Registration</h2>
            <p>
              To use the Service, you must sign in with a Google or GitHub account. You are responsible for:
            </p>
            <ul>
              <li>Maintaining the security of your OAuth provider account</li>
              <li>All activity that occurs under your account</li>
              <li>Notifying us of any unauthorized access</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>4. Payment and Billing</h2>
            <h3>Usage-Based Pricing</h3>
            <p>
              The Service operates on a usage-based model. You deposit funds and are charged per query
              based on actual AI provider costs plus a 10% service fee.
            </p>

            <h3>Deposits</h3>
            <ul>
              <li>Deposits are non-refundable</li>
              <li>Funds do not expire</li>
              <li>Minimum balance of $0.50 is required to submit queries</li>
            </ul>

            <h3>BYOK (Bring Your Own Key)</h3>
            <p>
              You may provide your own OpenRouter API key to bypass the credit system.
              In this case, you are billed directly by OpenRouter and we charge no additional fees.
            </p>
          </section>

          <section className="legal-section">
            <h2>5. Acceptable Use</h2>
            <p>You agree NOT to use the Service to:</p>
            <ul>
              <li>Generate content that is illegal, harmful, threatening, or hateful</li>
              <li>Attempt to extract training data or proprietary information from AI models</li>
              <li>Circumvent rate limits or abuse the Service infrastructure</li>
              <li>Impersonate others or misrepresent your identity</li>
              <li>Violate the terms of underlying AI providers (OpenRouter, OpenAI, Google, Anthropic, xAI)</li>
            </ul>
            <p>
              We reserve the right to suspend or terminate accounts that violate these terms.
            </p>
          </section>

          <section className="legal-section">
            <h2>6. AI-Generated Content</h2>
            <p className="important-notice">
              All responses are generated by AI models and should not be treated as professional advice.
            </p>
            <ul>
              <li>AI responses may contain errors, biases, or inaccuracies</li>
              <li>The Service does not guarantee the accuracy of any response</li>
              <li>Do not rely on AI responses for medical, legal, financial, or safety-critical decisions</li>
              <li>Always verify important information with qualified professionals</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>7. Intellectual Property</h2>
            <h3>Your Content</h3>
            <p>
              You retain ownership of the questions you submit. By using the Service, you grant us a
              license to process and store your content as necessary to provide the Service.
            </p>

            <h3>AI Responses</h3>
            <p>
              AI-generated responses are subject to the terms of the underlying AI providers.
              Generally, you may use responses for personal or commercial purposes, but specific
              restrictions may apply based on provider policies.
            </p>
          </section>

          <section className="legal-section">
            <h2>8. Third-Party Services</h2>
            <p>
              The Service relies on third-party providers:
            </p>
            <ul>
              <li><strong>OpenRouter</strong> - AI model routing and access</li>
              <li><strong>OpenAI, Google, Anthropic, xAI</strong> - AI model providers</li>
              <li><strong>Stripe</strong> - Payment processing</li>
              <li><strong>Supabase</strong> - Database hosting</li>
              <li><strong>Google, GitHub</strong> - Authentication</li>
            </ul>
            <p>
              Your use of the Service is also subject to these providers' terms and policies.
            </p>
          </section>

          <section className="legal-section">
            <h2>9. Limitation of Liability</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. TO THE MAXIMUM EXTENT
              PERMITTED BY LAW:
            </p>
            <ul>
              <li>We are not liable for any indirect, incidental, or consequential damages</li>
              <li>We are not liable for errors or inaccuracies in AI-generated content</li>
              <li>We are not liable for service interruptions or data loss</li>
              <li>Our total liability is limited to the amount you paid in the last 12 months</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>10. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless AI Council and its operators from any claims,
              damages, or expenses arising from your use of the Service or violation of these terms.
            </p>
          </section>

          <section className="legal-section">
            <h2>11. Service Availability</h2>
            <p>
              We strive to maintain high availability but do not guarantee uninterrupted service.
              The Service may be temporarily unavailable due to:
            </p>
            <ul>
              <li>Scheduled maintenance</li>
              <li>AI provider outages</li>
              <li>Technical issues</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>12. Modifications to Terms</h2>
            <p>
              We may update these terms at any time. Continued use of the Service after changes
              constitutes acceptance of the new terms. We will update the "Last updated" date
              when changes are made.
            </p>
          </section>

          <section className="legal-section">
            <h2>13. Termination</h2>
            <p>
              You may stop using the Service at any time. We may suspend or terminate your account
              for violations of these terms. Upon termination, your right to use the Service ceases
              immediately.
            </p>
          </section>

          <section className="legal-section">
            <h2>14. Governing Law</h2>
            <p>
              These terms are governed by applicable law. Any disputes will be resolved through
              appropriate legal channels.
            </p>
          </section>

          <section className="legal-section">
            <h2>15. Contact</h2>
            <p>
              For questions about these terms, please open an issue on our{' '}
              <a href="https://github.com/anbuneel/ai-council" target="_blank" rel="noopener noreferrer">
                GitHub repository
              </a>.
            </p>
          </section>
        </article>

        <footer className="legal-footer">
          <a href="/privacy" className="footer-link">Privacy Policy</a>
          <span className="footer-divider">|</span>
          <a href="/" className="footer-link">Return to AI Council</a>
        </footer>
      </div>
    </div>
  );
}

export default TermsOfService;
